@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ParserContext" as ParserContext LOGIC_COLOR
participant ":ABCParser" as ABCParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete 1")
activate LogicManager

LogicManager -> ParserContext: executeParserStrategyCommand("delete 1")
activate ParserContext

ParserContext -> ABCParser: parseCommand("delete 1")
activate ABCParser

create DeleteCommandParser
ABCParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> ABCParser
deactivate DeleteCommandParser

ABCParser -> DeleteCommandParser : parse("1")
activate DeleteCommandParser

create DeleteCommand
DeleteCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandParser : d
deactivate DeleteCommand

DeleteCommandParser --> ABCParser : d
deactivate DeleteCommandParser

ABCParser --> ParserContext : d
deactivate ABCParser

'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> ParserContext
destroy DeleteCommandParser

ParserContext --> LogicManager : d
deactivate ParserContext

LogicManager -> DeleteCommand : execute()
activate DeleteCommand

DeleteCommand -> Model : deletePerson(1)
activate Model

Model --> DeleteCommand
deactivate Model

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand

DeleteCommand --> LogicManager : result
deactivate DeleteCommand
note over of DeleteCommand: XYZCommand = Do take note that the CommandResult \nhas 2  consumers, one for the ":Logic" the other for the  ":UI"

LogicManager --> CommandResult: getLogicAction
CommandResult --> LogicManager:

[<--LogicManager
deactivate LogicManager
@enduml
