@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic {

Class ABCParser
Class XYZCommand
Class CommandResult
Class "{abstract}\nCommand" as Command
Class "{abstract}\nParserStrategy" as ParserStrategy
Class ParserContext
class PersonAdapter


Interface Logic <<Interface>>
Class LogicManager
}

package Model{
Class HiddenModel #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Logic

LogicManager .right.|> Logic
LogicManager -->"1" ParserContext
ParserContext -->"*" ParserStrategy
ABCParser *-up-> ParserStrategy
ABCParser ..> XYZCommand : creates >

XYZCommand -up-|> Command
XYZCommand  .up.> PersonAdapter : creates >
PersonAdapter  .down[hidden]. ABCParser
LogicManager .left.> Command : executes >

LogicManager --> Model
PersonAdapter -up-> Model
Command .right.> Model
note right of XYZCommand: XYZCommand = AddCommand, \nFindCommand, etc
note left of ABCParser : ABCParser = AddressBookParser, \nContactTabParser, etc

Logic ..> CommandResult
LogicManager .down.> CommandResult
Command .up.> CommandResult : produces >
@enduml
