@startuml Domain Model
skinparam style strictuml
skinparam groupInheritance 2

hide empty members

class "Financial Advisor" as FinancialAdvisor {
}

class "Client" as Client {

}

class "Contact Information" {
}

class "Policy" {
    Name
    Insurer Name
    Value Insured
    Yearly Premium
}

class "Asset" {
}

class "Liability" {
}

class "Equity Holding" {
    Name
    Type
    Value
    Remarks
}

class "Miscellaneous Information" {

}

class "Record Keeping Tool" {
}

class "Client Entry" {
}

class "Client Contact Details" {
    Name
    Phone
    Email
    Address
}

class "List of Assets" {
}


FinancialAdvisor -- "1" "Record Keeping Tool": has >
"Record Keeping Tool" -- "*" "Client Entry" : stores >

FinancialAdvisor -- "*" "Client": has >

"Client Entry" -- "1" "Client": records information of >

"Client" -- "*" "Policy" : purchases >
"Client" -- "*" "Equity Holding" : owns >
"Client" -- "1" "Contact Information" : has >
"Client" -- "*" "Miscellaneous Information" : has >

"Equity Holding" <|-- "Asset"
"Equity Holding" <|-- "Liability"

"Client Entry" *-- "Client Contact Details"
"Client Entry" *-- "List of Policies" :keeps >
"Client Entry" *-- "List of Assets" :keeps >
"Client Entry" *-- "List of Liabilities" :keeps >
"Client Entry" *-- "Financial Plan" :keeps >
"Client Entry" *-- "Notes"

"Client Contact Details" "1" -- "Contact Information": stores >
"List of Policies" -- "*""Policy": stores >
"List of Assets" -- "*""Asset": stores >
"List of Liabilities" -- "*""Liability": stores >
"Notes" -- "*" "Miscellaneous Information": stores >

"Financial Plan" -- "List of Policies": made from >
"Financial Plan" -- "List of Assets": made from >
"Financial Plan" -- "List of Liabilities": made from >
"Financial Plan" -- "Notes": made from >

@enduml