@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class UiState
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class PersonListPanel
Class PersonCard
Class CommandBox
Class ClientPanel
Class AttributePanel
Class AttributeTable
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
UiManager -right-> "1" UiState
MainWindow *-down->  "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" PersonListPanel
MainWindow --> "0..1" HelpWindow
MainWindow *--> "0..1" ClientPanel

PersonListPanel -down-> "*" PersonCard

ClientPanel --> "*" AttributeTable
ClientPanel --> "*" AttributePanel

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
PersonListPanel --|> UiPart
PersonCard --|> UiPart
HelpWindow --|> UiPart
ClientPanel --|> UiPart

PersonCard ..> Model
UiManager -right-> Logic
ClientPanel .right.> Logic
AttributeTable ..> Model

Model -[hidden]left- ClientPanel
Model -[hidden]down- AttributePanel
ClientPanel -[hidden]left- PersonListPanel
PersonListPanel -[hidden]left- HelpWindow
PersonListPanel -[hidden]up- Logic
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
PersonCard -[hidden]right- AttributePanel
PersonCard -[hidden]down- AttributePanel
PersonCard -[hidden]down- AttributeTable

MainWindow -[hidden]-|> UiPart
@enduml
