@startuml
!include ../style.puml

Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":ClientViewParser" as cvp LOGIC_COLOR
Participant ":TabParser" as ecp LOGIC_COLOR
Participant "command:EditCommand" as ec LOGIC_COLOR

[-> logic : execute
activate logic
logic -> cvp ++: parseCommand(commandText)
create ecp
cvp -> ecp
cvp -> ecp ++: parse(arguments)
create ec
ecp -> ec ++: index, editPersonDescriptor
ec --> ecp --
ecp --> cvp --: command
cvp --> logic --: command

@enduml
